nav:
    - Lectures: index.md
    - Bioinformatics:
        - bioinformatics
        - Lecture 01: "01"
        - Lecture 02A: "02A"
        - "Lecture 02B - Methodology": "02B"
        - Lecture 03A: "03A"
        - Lecture 03B: "03B"
        - Lecture 04A: "04A"
        - Lecture 04B: "04B"
        - Lecture 05A: "05A"
        - Lecture 05B: "05B"
        - Lecture 06A: "06A"
        - Lecture 06B: "06B"
        - Lecture 07A: "07A"
        - Lecture 07B: "07B"
        - Lecture 08A: "08A"
        - Lecture 08B: "08B"
    - Computational structural biology:
        - csb
        - "Structural biology<br>09A - Foundations": "09A"
        - "Lecture 09A - Methodology": "09B"
        - Lecture 10A: "10A"
        - Lecture 10B: "10B"
        - Lecture 11A: "11A"
        - Lecture 11B: "11B"
        - Lecture 12A: "12A"
        - Lecture 12B: "12B"
        - Lecture 13A: "13A"
        - Lecture 13B: "13B"
        - Lecture 14A: "14A"
        - Lecture 14B: "14B"
        - Lecture 14C: "14C"
